// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEGWFbvhm0ZfWddgmA1evxFycrZLU03Q',
    appId: '1:391162266621:web:166371c3c5d04cb3094f94',
    messagingSenderId: '391162266621',
    projectId: 'app-management-29321',
    authDomain: 'app-management-29321.firebaseapp.com',
    storageBucket: 'app-management-29321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxXRG_IYYIyDI7Tppb1W0kybf9NRre1Ng',
    appId: '1:391162266621:android:c103763674b3cbf6094f94',
    messagingSenderId: '391162266621',
    projectId: 'app-management-29321',
    storageBucket: 'app-management-29321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtJd3udXyheo-vd1MX8cEm4fX3HQ9wgY',
    appId: '1:391162266621:ios:d3c3f15787d76581094f94',
    messagingSenderId: '391162266621',
    projectId: 'app-management-29321',
    storageBucket: 'app-management-29321.appspot.com',
    iosBundleId: 'com.example.mobileAppRh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEtJd3udXyheo-vd1MX8cEm4fX3HQ9wgY',
    appId: '1:391162266621:ios:d3c3f15787d76581094f94',
    messagingSenderId: '391162266621',
    projectId: 'app-management-29321',
    storageBucket: 'app-management-29321.appspot.com',
    iosBundleId: 'com.example.mobileAppRh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChEGWFbvhm0ZfWddgmA1evxFycrZLU03Q',
    appId: '1:391162266621:web:64c45fbfb7d9b735094f94',
    messagingSenderId: '391162266621',
    projectId: 'app-management-29321',
    authDomain: 'app-management-29321.firebaseapp.com',
    storageBucket: 'app-management-29321.appspot.com',
  );
}
